services:
  # Prometheus for metrics collection
  prometheus:
    image: prom/prometheus:v2.37.0
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    ports:
      - "9099:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.enable-lifecycle'
      - '--storage.tsdb.retention.time=15d'
    restart: unless-stopped
    networks:
      - pipeline-network
    environment:
      - TZ=Asia/Kolkata
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:9090/-/healthy"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

  # InfluxDB for time series metrics storage
  influxdb:
    image: influxdb:2.7
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb2
      - influxdb_config:/etc/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=adminpassword123
      - DOCKER_INFLUXDB_INIT_ORG=metrics_org
      - DOCKER_INFLUXDB_INIT_BUCKET=metrics_bucket
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=my-super-secret-auth-token
      - TZ=Asia/Kolkata
    restart: unless-stopped
    networks:
      - pipeline-network
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8086/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # Telegraf for metrics processing and forwarding to InfluxDB
  telegraf:
    image: telegraf:1.28
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - influxdb
      - prometheus
    environment:
      - INFLUXDB_TOKEN=my-super-secret-auth-token
      - INFLUXDB_ORG=metrics_org
      - INFLUXDB_BUCKET=metrics_bucket
      - INFLUXDB_URL=http://influxdb:8086
      - TZ=Asia/Kolkata
    restart: unless-stopped
    networks:
      - pipeline-network
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
    healthcheck:
      test: ["CMD", "telegraf", "--test"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

networks:
  pipeline-network:
    driver: bridge

volumes:
  prometheus_data:
  influxdb_data:
  influxdb_config: