global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Remote write configuration to send metrics to Kafka
remote_write:
  - url: "http://prometheus-kafka-adapter:8080/receive"

# Scrape configurations
scrape_configs:
  - job_name: 'ipmi-exporter'
    static_configs:
      - targets: ['10.180.8.24:9290']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['10.180.8.24:9100']

  - job_name: 'dcgm-exporter'
    static_configs:
      - targets: ['10.180.8.24:9400']

  - job_name: 'slurm-exporter'
    static_configs:
      - targets: ['10.180.8.24:8080']
